name: 'Release Note Generator Action'
description: 'Release and generate github issue / jira issue'
inputs:
  github_token:
    description: 'github token'
    required: true
  jira_url:
    description: 'jira url'
    required: true
  jira_project:
    description: 'jira project'
    required: true
  jira_user:
      description: 'jira user'
      required: true
  jira_token:
    description: 'jira token'
    required: true
  base_version:
    description: 'base version'
    required: true
  current_version:
    description: 'current version'
    required: true
  configuration_path:
    description: 'config path'
    required: false
  github_label:
    description: 'github label'
    required: false
outputs:
  success:
    description: 'Generate success'
runs:
  using: 'node12'
  main: 'index.js'
